### PR TITLE
Fix the clairctl pull for schema 1 and 2

### PR DESCRIPTION
**Pull request by jgsqware**

### CODE REVIEW

**Comment by murat1985** [comment]
will test this one tomorrow, thanks @jgsqware

**Comment by jgsqware** [comment]
I've checked with an insecured registry configured to the docker daemon and it's working without the flag. 

I don't think the flag `--insecure`should be used. As I use the docker libs itself, I think it's better to use the same behavior as docker cli/daemon and use the configured insecure registry

**Comment by jgsqware** [comment]
@murat1985 When you have time you can test it on the master branch

**Comment by jgsqware** [comment]
closes #3

**Pull request merged**
